name: run-cypress-login-tests
run-name: ${{ github.actor }} is running Cypress Login Tests
on: [workflow_dispatch]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install docker
        uses: docker-practice/actions-setup-docker@master
      - name: Run the tests inside a docker container
        run: ./runner.sh
      - name: Upload the HTML results file as a workflow artifact
        uses: actions/upload-artifact@v3
        with:
          name: html-results-file
          path: mochawesome-report/mochawesome.html
