name: run-cypress-login-tests
run-name: ${{ github.actor }} is running Cypress Login Tests
on:
  workflow_dispatch:
    inputs:
      run-in-container:
        description: 'Run tests in a Docker container'
        default: true
        type: boolean
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install docker
        uses: docker-practice/actions-setup-docker@master
      - name: Run the tests inside a docker container
        run: ./runner.sh
        if: ${{ inputs.run-in-container }}
      - name: Run the tests without a container
        run: npm run cypress:run
        if: "${{ github.event.inputs.run-in-container != 'true' }}"
      - name: Upload the HTML results file as a workflow artifact
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-report
          path: mochawesome-report/
